# -*- coding: utf-8 -*-
"""Laptops_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lpy0lrrfMMrj8Vyll2ykfJ_XHGP8ime2

# **Laptops EDA**

The Laptops dataset is used from [Kaggle](https://www.kaggle.com/datasets/juanmerinobermejo/laptops-price-dataset)
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

!gdown 1eVE8Sy_7QCIlODu57CxtwARurfJR8vX5

"""**Fields in the dataset:**
\
**Laptop Name:** Unique identifier or model name of the laptop.
\
**Brand:** Laptop brand.
\
**Model:** Laptop model.
\
**CPU(Central Processing Unit):**  bold text Information about the processor (brand, model, and other characteristics).
\
**GPU (Graphics Processing Unit):** Information about the graphics card (brand, model, and specifications).
\
**RAM (Random Access Memory):** The amount of RAM for multitasking.
\
**Storage:** Drive type (HDD, SSD) and its capacity.
\
**Status:** Current status of the laptop (e.g. "New", "Refurbished").
\
**Touch:** Presence of a touch screen (Yes/No).
\
**Final Price:** Cost of the laptop.


"""

df=pd.read_csv('laptops.csv')

df.head(5)

df.info()

df.describe(include='all')

df.duplicated()

"""**Result** - No dublicates"""

df.columns

"""#Determination of empty values

"""

df.isna().mean()

"""**Result** - Storage type contains almost 1,9% empty values, GPU - 63% and Screen - 0,18%

"""

df.isnull().sum()

"""Result in numbers: GPU - 1371, Storage type - 42, Screen - 4

"""

sns.heatmap(df.isnull(), cbar=False, cmap="Blues")
plt.title("Missing values")
plt.show()

"""#Filling the empty values

Screen's missing values will replace with the median
"""

df['Screen'] = df['Screen'].fillna(df['Screen'].median())

df.isnull().sum()

"""Storage type will replace with the slosest values"""

df['Storage type'] = df['Storage type'].fillna('SSD')

df.isnull().sum()

"""GPU - will replace with "Unknown"
"""

df['GPU'] = df['GPU'].fillna('Unknown')

df.isnull().sum()

"""#Main statistical characteristics of the Price column (mean, median, standard deviation).

"""

df['Final Price'].mean()



df['Final Price'].median()

df['Final Price'].std()

"""#The visualization of the distribution of laptop prices


"""

sns.histplot(df['Final Price'], color = 'blue', kde = True)
plt.title('Price distribution ')
mean_Final_Price = df['Final Price'].mean()
median_Final_Price = df['Final Price'].median()
plt.axvline(mean_Final_Price, color='red', linestyle='--',label=f'Mean: {mean_Final_Price:.2f}')
plt.axvline(median_Final_Price, color='orange', linestyle='--', label=f'Median: {median_Final_Price:.2f}')
plt.legend()
plt.show()
plt.show()

"""#Definition of the outliers

"""

fig = px.box(df,y = 'Final Price')

fig.show()

"""# We will also conduct an analysis using the **interquartile range (IQR) method**

"""

Q1 = df['Final Price'].quantile(0.25)
Q3 = df['Final Price'].quantile(0.75)
IQR = Q3 - Q1
df_outliers = df[(df['Final Price']< (Q1 - 1.5*IQR)) |(df['Final Price'] > (Q3 + 1.5*IQR))]
print(f"Amount of the outliers: {len(df_outliers)}")
print(f"Percentage of the outliers: {len(df_outliers)/ len(df) * 100:.2f}%")
print(f"Mean of the outliers: {df_outliers['Final Price'].mean():_.2f}")
print(f"Median of the outliers: {df_outliers['Final Price'].median():_.2f}")
print(f"Highest value of the outliers: {df_outliers['Final Price'].max():_.2f}")
print(f"Lowest value of the outliers: {df_outliers['Final Price'].min():_.2f}")
print(f"Range of the outliers: {df_outliers['Final Price'].max() - df_outliers['Final Price'].min():_.2f}")
print(f"Standart diviation of the outliers: {df_outliers['Final Price'].std():_.2f}")
print()

"""**Description of the result:**
\
*Amount of the outliers*: 103 (4.77% of the total data) - a relatively small percentage.
This means that most of the data is within the normal range.
\
*Mean and median of the outliers*: The mean (4026.47) is slightly higher than the median (3799.00), which may indicate that there are outliers with higher values ​​that are pulling the mean up.
\
*Range of outliers*: The range of values ​​(3861.46) is quite wide. This may indicate that there is significant variation between outliers.
\
*Standard deviation* (685.50): A high standard deviation confirms that the outliers vary greatly.
"""

def highlight_outliers(val):
  if val < Q1 - 1.5 * IQR:
    return 'color:green'
  elif val > Q3 + 1.5 *IQR:
    return 'color:red'
  return 'color:black'

df_outliers[['Brand', 'Final Price']].style.map(
    highlight_outliers,
    subset = ['Final Price']

).format({'Final Price': '{:.2f}'})

"""# Dependency between Price and other features

"""

plt.figure(figsize=(8,6))
sns.stripplot(
    x = 'Final Price', y = 'Brand',
    data = df, jitter = True,
    alpha = 0.7, size = 7
)
plt.title('Dependency between Final Price and Brand')
plt.show()

plt.figure(figsize=(8,6))
sns.stripplot(
    x = 'Storage', y = 'Final Price',
    data = df, jitter = True,
    alpha = 0.7, size = 7
)
plt.title('Dependency Final Price and Storage')
plt.show()

plt.figure(figsize=(8,6))
sns.stripplot(
    x = 'RAM', y = 'Final Price',
    data = df, jitter = True,
    alpha = 0.7, size = 7
)
plt.title('Dependency Final Price and RAM')
plt.show()

"""#**Correlation hitmap** for numerical features and identification of features that influence Price the most

"""

numerical_df = df.select_dtypes(include = ['number'])

correlation_matrix = numerical_df.corr()
print(correlation_matrix)

fig = px.imshow(
    correlation_matrix,
    text_auto = True,
    color_continuous_scale='RdBu',
    zmin=-1, zmax=1,
    title = 'Correlation Heatmap'
)
fig.show()

"""Result - RAM, Storage, Screen (in descending order) affect the Final Price

#Data summary sheets

Grouping by Brands, Average price of the laptops by Brands.
"""

df.groupby('Brand')['Final Price'].mean()

"""
A pivot table showing the Average price of laptops depending on Brand and Status
"""

pd.pivot_table(

    df,

    values='Final Price',

    index='Brand',

    columns='Status',

    aggfunc='mean'

)

"""#Visualisation"""

aver_price = df.groupby('Brand', as_index=False)['Final Price'].mean()
plt.figure(figsize=(14,6))
plt.bar(aver_price['Brand'], aver_price['Final Price'])

plt.xlabel(' Brand')

plt.ylabel('Average price')

plt.title('Average price of laptops by Brand')
plt.xticks(rotation=45)

plt.show()

price_touch = df.groupby('Touch', as_index=False)['Final Price'].mean()

plt.bar(price_touch['Touch'], price_touch['Final Price'])

plt.xlabel(' Touch screen (No/Yes)')

plt.ylabel('Average price ')

plt.title('Average price of laptop by Brand depends on Touch screen')

plt.show()

"""# **Conclusion**

The purpose of this project is to provide an analysis of the Laptops dataset.
\
By conducting Exploratory Data Analysis(EDA) we have obtained important insights that can help make more informed desicions about this type of product.

#Thank You for your attention!
"""